export const STRINGS = {
  ENTER_PLAYER_NAMES: "Enter Player Names",
  ENTER_PLAYER1_NAME: "Player 1 Name: ",
  ENTER_PLAYER2_NAME: "Player 2 Name: ",
  ERROR_ENTER_NAME_FOR_PLAYERS: "Please enter a name for both players.",
  IT_IS_NOT_YOUR_TURN: "It's not your turn.",
  YOU_ARE_BLOCKED: "You are blocked.",
  INVALID_MOVE: "Invalid move. Play a card with the same suit or value.",
  YOU_MUST_DRAW_REQUIRED_CARDS:
    "You must draw the required cards before playing.",
  DEAL_CARDS: "Deal Cards",
  DRAW_CARD: "Draw Card",
  DISCARD_PILE: "Discard Pile",
  START_GAME: "Start Game",
  FETCH_NEW_DECK: "Fetch New Deck",
  IT_IS_YOUR_TURN: "It's your turn",
  IT_IS_A_DRAW: "It's a draw!",
  NO_ONE_WINS: "No one wins!",
  DECK_IS_SHUFFLED: "The deck has been shuffled, you can deal the cards now.",
};
